<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Applicants - {{ $job->title }}</title>
    <style>
        /* Font */
        body { font-family: DejaVu Sans, sans-serif; color: #333; margin: 0; padding: 20px; }

        /* Header */
        header { text-align: center; margin-bottom: 30px; }
        header h1 { margin: 0; font-size: 24px; color: #2c3e50; }
        header p { margin: 2px 0; font-size: 14px; color: #555; }

        /* Table */
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; font-size: 12px; }
        th { background-color: #f4f4f4; color: #2c3e50; }
        tr:nth-child(even) { background-color: #f9f9f9; }

        /* Links */
        a { color: #2980b9; text-decoration: none; }
        a:hover { text-decoration: underline; }

        /* Footer */
        footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 10px; color: #888; }
    </style>
</head>
<body>
    <header>
        <h1>Applicants for: {{ $job->title }}</h1>
        <p><strong>Company:</strong> {{ $company->name }}</p>
        <p><strong>Total Applicants:</strong> {{ count($applicants) }}</p>
        <p><strong>Generated On:</strong> {{ now()->format('Y-m-d H:i') }}</p>
    </header>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Resume</th>
                <th>Applied On</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($applicants as $index => $a)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $a->full_name }}</td>
                    <td>{{ $a->email }}</td>
                    <td>{{ $a->cell_number }}</td>
                    <td>{{ $a->address }}</td>
                    <td>
                        @if($a->resume)
                            <a href="{{ url($a->resume) }}">Download</a>
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $a->created_at ? $a->created_at->format('Y-m-d H:i') : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        Generated by {{ config('app.name') }} | Page {PAGE_NUM} of {PAGE_COUNT}
    </footer>
</body>
</html>
